/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Liveness probe: the process runs and its event loop answers.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe with the state of the database and every upstream service.
         */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform */
        get: operations["platform_api_v1_platform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Sign in with a username and password.
         *
         *     An unknown user, a wrong password and a blocked account get the same 401. After too
         *     many failures for one account name or one client the answer is 429 with Retry-After,
         *     again whether or not the account exists.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a refresh token for a new pair; the presented token becomes unusable.
         *
         *     Presenting an exchanged token again closes the whole session.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Close the session of the presented refresh token (body or cookie) or bearer token.
         *
         *     Always answers 200, so it reveals nothing about the token.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The signed-in user with their current role.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change the signed-in user's password.
         *
         *     Every session of the user is closed, including this one; the response carries a
         *     fresh session. Wrong current passwords count toward the sign-in throttle.
         */
        post: operations["change_password_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Status
         * @description Return the current boiler and turbine state from live gRPC.
         */
        get: operations["get_system_status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plant State
         * @description The latest plant step: measurements, valves, emissions, health, faults.
         */
        get: operations["get_plant_state_api_v1_plant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Simulation Status */
        get: operations["get_simulation_status_api_v1_simulation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_v1_simulation_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_api_v1_simulation_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_simulation_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Speed */
        post: operations["set_speed_api_v1_simulation_speed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step
         * @description Advance a paused simulation by whole steps.
         */
        post: operations["step_api_v1_simulation_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Scenario
         * @description Restart the plant from a scenario; the PLC follows the new run.
         */
        post: operations["load_scenario_api_v1_simulation_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/faults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Fault
         * @description Inject a labelled fault; the physics engine validates target and severity.
         */
        post: operations["inject_fault_api_v1_simulation_faults_post"];
        /** Clear All Faults */
        delete: operations["clear_all_faults_api_v1_simulation_faults_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/faults/{fault_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Fault */
        delete: operations["clear_fault_api_v1_simulation_faults__fault_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenario Runs
         * @description Scenario loads and fault changes, newest first, with who made them.
         */
        get: operations["list_scenario_runs_api_v1_simulation_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands/valve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Valve Command
         * @description Send a manual valve command to the PLC; the PLC switches to MANUAL.
         */
        post: operations["send_valve_command_api_v1_commands_valve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Load Demand
         * @description Set the electrical load the PLC drives the unit to in AUTO.
         */
        post: operations["set_load_demand_api_v1_commands_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Control Mode
         * @description Switch the PLC between AUTO and MANUAL, or trip the unit.
         */
        post: operations["set_control_mode_api_v1_commands_mode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands/setpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Setpoints
         * @description Update live PLC setpoints and return the acceptance status.
         */
        post: operations["update_setpoints_api_v1_commands_setpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Emergency Stop
         * @description Reset the PLC emergency stop latch once its cause is gone; back to AUTO.
         *
         *     The reset is recorded under the authenticated user. An operator_id in the body no
         *     longer overrides that; it is kept in the audit detail as a note.
         */
        post: operations["reset_emergency_stop_api_v1_commands_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plc/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plc Status
         * @description Current PLC mode, targets, loops, alarm conditions and reset permission.
         */
        get: operations["get_plc_status_api_v1_plc_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Telemetry over a bounded range at a resolution chosen from its length.
         *
         *     The range is split into standard windows (1 s … 1 day) so that it fits in `limit`
         *     points; each point is the mean of its window.
         */
        get: operations["get_history_api_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kpis
         * @description KPIs of the unit over a range: the last 15 minutes by default, at most 90 days.
         */
        get: operations["get_kpis_api_v1_kpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alarms
         * @description Recent alarms; with active_only, open alarms with critical and unacknowledged first.
         */
        get: operations["list_alarms_api_v1_alarms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alarm History
         * @description Alarm history with filters, newest first, paged.
         */
        get: operations["alarm_history_api_v1_alarms_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/ack-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge All
         * @description Acknowledge every unacknowledged alarm, optionally of one severity.
         */
        post: operations["acknowledge_all_api_v1_alarms_ack_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{alarm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alarm
         * @description One alarm with every state change it went through.
         */
        get: operations["get_alarm_api_v1_alarms__alarm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{alarm_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge Alarm
         * @description Acknowledge one alarm; refused if it is already acknowledged.
         */
        post: operations["acknowledge_alarm_api_v1_alarms__alarm_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Entries
         * @description Audit entries matching every given filter.
         */
        get: operations["list_audit_entries_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Accounts ordered by username, with role and open sessions.
         */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create an active account with one role.
         */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Change the role or block/unblock; the user's sessions are closed.
         */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Set a new password for a user; the user's sessions are closed.
         */
        post: operations["reset_password_api_v1_users__user_id__password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Sessions
         * @description Sign a user out everywhere.
         */
        post: operations["revoke_sessions_api_v1_users__user_id__revoke_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcknowledgeAllRequest
         * @description Request body for POST /api/v1/alarms/ack-all.
         */
        AcknowledgeAllRequest: {
            /**
             * Comment
             * @default
             */
            comment: string;
            /**
             * Severity
             * @description Only alarms of this severity; all when omitted.
             */
            severity?: ("warning" | "critical") | null;
        };
        /**
         * AcknowledgeRequest
         * @description Request body for POST /api/v1/alarms/{alarm_id}/ack.
         */
        AcknowledgeRequest: {
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /**
         * AcknowledgeResponse
         * @description Result of an acknowledgement.
         */
        AcknowledgeResponse: {
            /** Accepted */
            accepted: boolean;
            /** Reason */
            reason: string;
            /** Timestamp Ms */
            timestamp_ms: number;
            /** Alarms */
            alarms: components["schemas"]["AlarmResponse"][];
        };
        /** ActuatorStateResponse */
        ActuatorStateResponse: {
            /** Fuel Valve Command */
            fuel_valve_command: number;
            /** Fuel Valve Position */
            fuel_valve_position: number;
            /** Feedwater Valve Command */
            feedwater_valve_command: number;
            /** Feedwater Valve Position */
            feedwater_valve_position: number;
            /** Steam Valve Command */
            steam_valve_command: number;
            /** Steam Valve Position */
            steam_valve_position: number;
            /** Spray Valve Command */
            spray_valve_command: number;
            /** Spray Valve Position */
            spray_valve_position: number;
        };
        /** AlarmConditionResponse */
        AlarmConditionResponse: {
            /** Key */
            key: string;
            /** Parameter */
            parameter: string;
            /** Severity */
            severity: string;
            /** Direction */
            direction: string;
            /** Value */
            value: number;
            /** Threshold */
            threshold: number;
            /** Message */
            message: string;
            /** Since Ms */
            since_ms: number;
        };
        /**
         * AlarmDetailResponse
         * @description An alarm with its transitions, oldest first.
         */
        AlarmDetailResponse: {
            alarm: components["schemas"]["AlarmResponse"];
            /** Transitions */
            transitions: components["schemas"]["AlarmTransitionResponse"][];
        };
        /**
         * AlarmPageResponse
         * @description A page of alarm history.
         */
        AlarmPageResponse: {
            /** Items */
            items: components["schemas"]["AlarmResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * AlarmResponse
         * @description An alarm with its lifecycle.
         *
         *     `alarm_id`, `occurred_at_ms`, `acknowledged` and `cleared` keep their earlier
         *     meaning; `state` is the full lifecycle state.
         */
        AlarmResponse: {
            /**
             * Alarm Id
             * @description The alarm id as a string.
             */
            alarm_id: string;
            /** Id */
            id: number;
            /**
             * Key
             * @description Condition identity; one open alarm per key.
             */
            key: string;
            /** Source Service */
            source_service: string;
            /** Severity */
            severity: string;
            /** Parameter */
            parameter: string;
            /** Direction */
            direction: string;
            /** Unit */
            unit: string;
            /**
             * State
             * @enum {string}
             */
            state: "ACTIVE_UNACK" | "ACTIVE_ACK" | "CLEARED_UNACK" | "CLEARED";
            /**
             * Value
             * @description Latest value, in `unit`.
             */
            value: number;
            /** Threshold */
            threshold: number;
            /** Action */
            action: string;
            /** Message */
            message: string;
            /** Topic */
            topic: string;
            /**
             * Occurred At Ms
             * @description Same as raised_at_ms.
             */
            occurred_at_ms: number;
            /** Raised At Ms */
            raised_at_ms: number;
            /** Cleared At Ms */
            cleared_at_ms: number | null;
            /** Acknowledged */
            acknowledged: boolean;
            /** Acknowledged At Ms */
            acknowledged_at_ms: number | null;
            /** Acknowledged By */
            acknowledged_by: string | null;
            /** Ack Comment */
            ack_comment: string | null;
            /**
             * Cleared
             * @description The condition has ended.
             */
            cleared: boolean;
            /** Occurrence Count */
            occurrence_count: number;
            /** Updated At Ms */
            updated_at_ms: number;
        };
        /**
         * AlarmTransitionResponse
         * @description One state change of an alarm.
         */
        AlarmTransitionResponse: {
            /** Id */
            id: number;
            /** Alarm Id */
            alarm_id: number;
            /** From State */
            from_state: ("ACTIVE_UNACK" | "ACTIVE_ACK" | "CLEARED_UNACK" | "CLEARED") | null;
            /**
             * To State
             * @enum {string}
             */
            to_state: "ACTIVE_UNACK" | "ACTIVE_ACK" | "CLEARED_UNACK" | "CLEARED";
            /** At Ms */
            at_ms: number;
            /**
             * Actor
             * @description Source service or the user who acknowledged.
             */
            actor: string;
            /** Comment */
            comment: string | null;
            /** Value */
            value: number | null;
        };
        /**
         * AuditPageResponse
         * @description A page of audit entries, newest first.
         */
        AuditPageResponse: {
            /** Items */
            items: components["schemas"]["AuditResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * AuditResponse
         * @description Audit log entry returned by the API gateway.
         */
        AuditResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number | null;
            /**
             * Username
             * @description Acting user.
             */
            username: string | null;
            /**
             * Role
             * @description Role the user held when acting.
             */
            role: string | null;
            /** Ip Address */
            ip_address: string;
            /** Method */
            method: string;
            /** Endpoint */
            endpoint: string;
            /** Request Body Hash */
            request_body_hash: string | null;
            /** Response Status */
            response_status: number;
            /** Duration Ms */
            duration_ms: number;
            /** Timestamp Ms */
            timestamp_ms: number;
            /** Detail */
            detail: string | null;
            /**
             * Outcome
             * @description How the action ended, e.g. accepted, refused: <reason>.
             */
            outcome: string | null;
        };
        /** BoilerStateResponse */
        BoilerStateResponse: {
            /** Pressure Pa */
            pressure_pa: number;
            /** Water Level M */
            water_level_m: number;
            /** Water Temp K */
            water_temp_k: number;
            /** Flue Gas Temp K */
            flue_gas_temp_k: number;
            /** Internal Energy J */
            internal_energy_j: number;
            /** Timestamp Ms */
            timestamp_ms: number;
            /**
             * Quality
             * @description Worst boiler instrument quality.
             * @enum {string}
             */
            quality: "good" | "uncertain" | "bad";
            /** Fuel Flow Kg S */
            fuel_flow_kg_s: number;
            /** Feedwater Flow Kg S */
            feedwater_flow_kg_s: number;
            /** Drum Steam Flow Kg S */
            drum_steam_flow_kg_s: number;
            /** Spray Flow Kg S */
            spray_flow_kg_s: number;
            /** Superheater Outlet Temp K */
            superheater_outlet_temp_k: number;
            /** Economizer Outlet Temp K */
            economizer_outlet_temp_k: number;
            /** Stack Temp K */
            stack_temp_k: number;
            /** Heat Release W */
            heat_release_w: number;
            /** Boiler Efficiency */
            boiler_efficiency: number;
            /** Feedwater Temp K */
            feedwater_temp_k: number;
            /** Relief Flow Kg S */
            relief_flow_kg_s: number;
        };
        /**
         * BoilerStatusResponse
         * @description Current boiler state as returned by GET /api/v1/status.
         *     All values in SI units, matching BoilerStateMsg fields exactly
         *     so the gateway can populate this schema directly from protobuf.
         */
        BoilerStatusResponse: {
            /**
             * Pressure Pa
             * @description Drum pressure [Pa].
             */
            pressure_pa: number;
            /**
             * Water Level M
             * @description Water level in drum [m].
             */
            water_level_m: number;
            /**
             * Water Temp K
             * @description Bulk water temperature [K].
             */
            water_temp_k: number;
            /**
             * Flue Gas Temp K
             * @description Flue gas temperature [K].
             */
            flue_gas_temp_k: number;
            /**
             * Internal Energy J
             * @description Total internal energy [J].
             */
            internal_energy_j: number;
            /**
             * Timestamp Ms
             * @description UTC epoch milliseconds.
             */
            timestamp_ms: number;
            /**
             * Quality
             * @description Sensor quality: good | uncertain | bad.
             */
            quality: string;
        };
        /**
         * CommandAckResponse
         * @description Response body for all command endpoints.
         *     Mirrors CommandAck from the protobuf schema.
         *     If accepted=False, reason explains why the command was rejected
         *     (e.g. value out of safe range, safety interlock active).
         */
        CommandAckResponse: {
            /**
             * Accepted
             * @description True if the command was accepted.
             */
            accepted: boolean;
            /**
             * Reason
             * @description Rejection reason. Empty string when accepted=True.
             * @default
             */
            reason: string;
            /**
             * Timestamp Ms
             * @description UTC epoch milliseconds.
             */
            timestamp_ms: number;
        };
        /** ComponentHealth */
        ComponentHealth: {
            /** Name */
            name: string;
            /**
             * State
             * @enum {string}
             */
            state: "up" | "down";
            /** Required */
            required: boolean;
            /**
             * Latency Ms
             * @description Round trip of the check.
             */
            latency_ms: number | null;
        };
        /** CondenserResponse */
        CondenserResponse: {
            /** Backpressure Pa */
            backpressure_pa: number;
            /** Condensate Temp K */
            condensate_temp_k: number;
            /** Cooling Water Temp In K */
            cooling_water_temp_in_k: number;
            /** Cooling Water Temp Out K */
            cooling_water_temp_out_k: number;
            /** Heat Rejected W */
            heat_rejected_w: number;
            /** Loading */
            loading: number;
        };
        /** ControlLoopResponse */
        ControlLoopResponse: {
            /** Name */
            name: string;
            /** Setpoint */
            setpoint: number;
            /** Measurement */
            measurement: number;
            /** Output */
            output: number;
            /** Unit */
            unit: string;
        };
        /**
         * ControlModeRequest
         * @description Request body for POST /api/v1/commands/mode.
         *     Requires minimum role: operator. "estop" is a manual trip; only a reset clears it.
         */
        ControlModeRequest: {
            /**
             * Mode
             * @description PLC operating mode to switch to.
             * @enum {string}
             */
            mode: "auto" | "manual" | "estop";
        };
        /** EmissionsResponse */
        EmissionsResponse: {
            /** Co2 Kg S */
            co2_kg_s: number;
            /** Nox Kg S */
            nox_kg_s: number;
            /** Co Kg S */
            co_kg_s: number;
            /** Nox Ppmv */
            nox_ppmv: number;
            /** Co2 Intensity Kg Per Mwh */
            co2_intensity_kg_per_mwh: number;
        };
        /** EquipmentHealthResponse */
        EquipmentHealthResponse: {
            /** Turbine Hours */
            turbine_hours: number;
            /** Turbine Starts */
            turbine_starts: number;
            /** Turbine Damage */
            turbine_damage: number;
            /** Boiler Tube Hours */
            boiler_tube_hours: number;
            /** Boiler Tube Damage */
            boiler_tube_damage: number;
            /** Pump Hours */
            pump_hours: number;
            /** Overall Health Pct */
            overall_health_pct: number;
            /** Maintenance Alarm */
            maintenance_alarm: boolean;
            /** Maintenance Critical */
            maintenance_critical: boolean;
        };
        /** FaultAckResponse */
        FaultAckResponse: {
            /** Accepted */
            accepted: boolean;
            /** Reason */
            reason: string;
            /** Timestamp Ms */
            timestamp_ms: number;
            /** Faults */
            faults: components["schemas"]["FaultResponse"][];
        };
        /** FaultRequest */
        FaultRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "burner_fouling" | "steam_leak" | "feedwater_pump_failure" | "valve_stuck" | "sensor_drift" | "sensor_failure";
            /**
             * Target
             * @description Valve (fuel, feedwater, steam, spray) or sensor id, if the kind needs one.
             * @default
             */
            target: string;
            /**
             * Severity
             * @default 1
             */
            severity: number;
            /**
             * Ramp S
             * @default 0
             */
            ramp_s: number;
        };
        /** FaultResponse */
        FaultResponse: {
            /** Fault Id */
            fault_id: string;
            /** Kind */
            kind: string;
            /** Target */
            target: string;
            /** Severity */
            severity: number;
            /** Ramp S */
            ramp_s: number;
            /** Started At S */
            started_at_s: number;
            /**
             * Intensity
             * @description 0 at onset, 1 once fully developed.
             */
            intensity: number;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryPointResponse
         * @description One historical telemetry row returned from InfluxDB.
         */
        HistoryPointResponse: {
            /**
             * Measurement
             * @description Influx measurement name.
             */
            measurement: string;
            /**
             * Timestamp Ms
             * @description UTC epoch milliseconds.
             */
            timestamp_ms: number;
            /**
             * Values
             * @description Field/value map for the historical row.
             */
            values?: {
                [key: string]: number | string | null;
            };
        };
        /**
         * HistoryResponse
         * @description Historical telemetry over a bounded range at an automatic resolution.
         */
        HistoryResponse: {
            /** Measurement */
            measurement: string;
            /**
             * Start Ms
             * @description Range start [UTC epoch ms].
             */
            start_ms: number;
            /**
             * End Ms
             * @description Range end [UTC epoch ms].
             */
            end_ms: number;
            /**
             * Window S
             * @description Each point is the mean over a window this long [s].
             */
            window_s: number;
            /** Points */
            points: components["schemas"]["HistoryPointResponse"][];
        };
        /** KpiResponse */
        KpiResponse: {
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /**
             * Source
             * @description raw | aggregate (one-minute means).
             */
            source: string;
            /**
             * Samples
             * @description Plant status samples in the range.
             */
            samples: number;
            /** Mean Electrical Power W */
            mean_electrical_power_w: number | null;
            /** Mean Fuel Heat Input W */
            mean_fuel_heat_input_w: number | null;
            /**
             * Net Efficiency
             * @description 0..1
             */
            net_efficiency: number | null;
            /**
             * Boiler Efficiency
             * @description 0..1
             */
            boiler_efficiency: number | null;
            /**
             * Turbine Heat Rate J Per J
             * @description Heat to the cycle per unit of electricity [J/J].
             */
            turbine_heat_rate_j_per_j: number | null;
            /**
             * Plant Heat Rate J Per J
             * @description Fuel heat per unit of electricity [J/J].
             */
            plant_heat_rate_j_per_j: number | null;
            /**
             * Co2 Intensity Kg Per J
             * @description CO2 per unit of electricity [kg/J].
             */
            co2_intensity_kg_per_j: number | null;
            /** Mean Nox Ppmv */
            mean_nox_ppmv: number | null;
            /** Peak Nox Ppmv */
            peak_nox_ppmv: number | null;
            /** Mean Health Pct */
            mean_health_pct: number | null;
            /** Lowest Health Pct */
            lowest_health_pct: number | null;
        };
        /**
         * LoadDemandRequest
         * @description Request body for POST /api/v1/commands/load.
         *     Requires minimum role: operator. The unit ramps to the new load at 30 MW/min.
         */
        LoadDemandRequest: {
            /**
             * Load W
             * @description Electrical load target [W], 0 – 300 MW.
             * @example 300000000
             */
            load_w: number;
        };
        /**
         * LoginRequest
         * @description Request body for POST /auth/login.
         *     Both fields are required. Passwords are never logged or stored
         *     in plain text — only the Argon2id hash is persisted.
         */
        LoginRequest: {
            /**
             * Username
             * @description Username registered in the system.
             * @example operator1
             */
            username: string;
            /**
             * Password
             * @description Plain-text password (transmitted over TLS only).
             * @example s3cur3P@ssword
             */
            password: string;
        };
        /**
         * LogoutRequest
         * @description Request body for POST /auth/logout; omit it to use the refresh cookie or the bearer
         *     token. The whole session of the token is closed.
         */
        LogoutRequest: {
            /**
             * Refresh Token
             * @description Refresh token of the session.
             */
            refresh_token?: string | null;
        };
        /**
         * MessageResponse
         * @description Generic single-message response used across multiple endpoints.
         */
        MessageResponse: {
            /**
             * Message
             * @description Human-readable status message.
             */
            message: string;
        };
        /**
         * PLCStatusResponse
         * @description Mode, targets, working setpoints, loops and alarm conditions of the PLC.
         */
        PLCStatusResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "manual" | "estop";
            /** Emergency Stop Active */
            emergency_stop_active: boolean;
            trip_cause: components["schemas"]["TripCause"] | null;
            /** Reset Permitted */
            reset_permitted: boolean;
            /** Reset Blockers */
            reset_blockers: string[];
            /** Load Demand W */
            load_demand_w: number;
            /** Load Setpoint W */
            load_setpoint_w: number;
            /** @description Targets set by an engineer. */
            setpoints: components["schemas"]["SetpointValues"];
            /** @description Working setpoints ramping toward the targets. */
            active_setpoints: components["schemas"]["SetpointValues"];
            latest_command: components["schemas"]["ValveCommandValues"];
            /** Active Conditions */
            active_conditions: components["schemas"]["AlarmConditionResponse"][];
            /** Loops */
            loops: components["schemas"]["ControlLoopResponse"][];
            /** Warning Count */
            warning_count: number;
            /** Trip Count */
            trip_count: number;
            /** Run Id */
            run_id: number;
        };
        /**
         * PasswordChangeRequest
         * @description Request body for POST /auth/password.
         */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /** New Password */
            new_password: string;
        };
        /** PerformanceResponse */
        PerformanceResponse: {
            /** Fuel Heat Input W */
            fuel_heat_input_w: number;
            /** Heat To Cycle W */
            heat_to_cycle_w: number;
            /**
             * Net Efficiency
             * @description 0..1; 0 when not generating.
             */
            net_efficiency: number;
            /** Turbine Heat Rate J Per J */
            turbine_heat_rate_j_per_j: number;
            /** Plant Heat Rate J Per J */
            plant_heat_rate_j_per_j: number;
            /** Co2 Intensity Kg Per J */
            co2_intensity_kg_per_j: number;
            /** Boiler Efficiency */
            boiler_efficiency: number;
            /**
             * Electrical Power W
             * @description True output, not the reading.
             */
            electrical_power_w: number;
        };
        /**
         * PlantStateResponse
         * @description Everything the physics engine publishes about the plant at one step.
         */
        PlantStateResponse: {
            /** Timestamp Ms */
            timestamp_ms: number;
            simulation: components["schemas"]["SimulationStatusResponse"];
            boiler: components["schemas"]["BoilerStateResponse"];
            turbine: components["schemas"]["TurbineStateResponse"];
            actuators: components["schemas"]["ActuatorStateResponse"];
            emissions: components["schemas"]["EmissionsResponse"];
            condenser: components["schemas"]["CondenserResponse"];
            health: components["schemas"]["EquipmentHealthResponse"];
            performance: components["schemas"]["PerformanceResponse"];
            /** Faults */
            faults: components["schemas"]["FaultResponse"][];
            /** Sensors */
            sensors: components["schemas"]["SensorStatusResponse"][];
        };
        /** PlatformResponse */
        PlatformResponse: {
            readiness: components["schemas"]["ReadinessResponse"];
            /**
             * Telemetry Age S
             * @description Seconds since the gateway last received a plant state.
             */
            telemetry_age_s: number | null;
            /** Websocket Clients */
            websocket_clients: number;
        };
        /**
         * ProfileResponse
         * @description The signed-in user, as the gateway sees them now.
         */
        ProfileResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Session Id */
            session_id: string;
            /** Access Expires At Ms */
            access_expires_at_ms: number;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded" | "not_ready";
            /** Components */
            components: components["schemas"]["ComponentHealth"][];
            /** Checked At Ms */
            checked_at_ms: number;
        };
        /**
         * RefreshRequest
         * @description Request body for POST /auth/refresh; omit it to use the refresh cookie.
         */
        RefreshRequest: {
            /**
             * Refresh Token
             * @description Refresh token to exchange.
             */
            refresh_token?: string | null;
        };
        /**
         * ResetRequest
         * @description Request body for POST /api/v1/commands/reset.
         */
        ResetRequest: {
            /**
             * Operator Id
             * @description Operator identifier recorded in the reset audit trail.
             * @default
             */
            operator_id: string;
        };
        /** ScenarioListResponse */
        ScenarioListResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioResponse"][];
            /** Current */
            current: string;
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /** Name */
            name: string;
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /** ScenarioRunPageResponse */
        ScenarioRunPageResponse: {
            /** Items */
            items: components["schemas"]["ScenarioRunResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ScenarioRunResponse */
        ScenarioRunResponse: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "scenario" | "fault_injected" | "fault_cleared";
            /** Scenario */
            scenario: string;
            /** Run Id */
            run_id: number;
            /** Fault Id */
            fault_id: string | null;
            /** Fault Label */
            fault_label: string | null;
            /** Severity */
            severity: number | null;
            /** Simulation Time S */
            simulation_time_s: number;
            /** User Id */
            user_id: number | null;
            /** Username */
            username: string;
            /** At Ms */
            at_ms: number;
        };
        /** SensorStatusResponse */
        SensorStatusResponse: {
            /** Sensor Id */
            sensor_id: string;
            /**
             * Quality
             * @enum {string}
             */
            quality: "good" | "uncertain" | "bad";
            /** Measured Value */
            measured_value: number;
        };
        /** SessionsRevokedResponse */
        SessionsRevokedResponse: {
            /** User Id */
            user_id: number;
            /** Revoked Tokens */
            revoked_tokens: number;
        };
        /**
         * SetpointRequest
         * @description Request body for POST /api/v1/commands/setpoint.
         *     Requires minimum role: engineer.
         *     All three setpoints must be provided together — the cascade PID
         *     controller uses them as a consistent set.
         */
        SetpointRequest: {
            /**
             * Pressure Pa
             * @description Target drum pressure [Pa]. Safe range: 50–185 bar.
             * @example 14000000
             */
            pressure_pa: number;
            /**
             * Water Level M
             * @description Target water level in drum [m].
             * @example 4.8
             */
            water_level_m: number;
            /**
             * Steam Temp K
             * @description Target steam temperature [K]. Safe range: 400–848 K.
             * @example 811
             */
            steam_temp_k: number;
        };
        /** SetpointValues */
        SetpointValues: {
            /** Pressure Pa */
            pressure_pa: number;
            /** Water Level M */
            water_level_m: number;
            /** Steam Temp K */
            steam_temp_k: number;
        };
        /** SimulationAckResponse */
        SimulationAckResponse: {
            /** Accepted */
            accepted: boolean;
            /** Reason */
            reason: string;
            /** Timestamp Ms */
            timestamp_ms: number;
            status: components["schemas"]["SimulationStatusResponse"];
        };
        /** SimulationStatusResponse */
        SimulationStatusResponse: {
            /**
             * Run State
             * @enum {string}
             */
            run_state: "running" | "paused";
            /** Speed Factor */
            speed_factor: number;
            /** Simulation Time S */
            simulation_time_s: number;
            /** Step Count */
            step_count: number;
            /** Scenario */
            scenario: string;
            /**
             * Run Id
             * @description Changes whenever a scenario is loaded.
             */
            run_id: number;
            /** Step S */
            step_s: number;
        };
        /** SpeedRequest */
        SpeedRequest: {
            /**
             * Speed Factor
             * @description Simulated seconds per wall-clock second.
             */
            speed_factor: number;
        };
        /** StepRequest */
        StepRequest: {
            /**
             * Steps
             * @description Only while paused.
             */
            steps: number;
        };
        /**
         * SystemStatusResponse
         * @description Full system state: boiler + turbine combined.
         *     Returned by GET /api/v1/status.
         */
        SystemStatusResponse: {
            boiler: components["schemas"]["BoilerStatusResponse"];
            turbine: components["schemas"]["TurbineStatusResponse"];
        };
        /**
         * TokenResponse
         * @description Response body for POST /auth/login, POST /auth/refresh and POST /auth/password.
         *     access_token  — short-lived (15 min), used in the Authorization header; keep it in
         *                     memory.
         *     refresh_token — valid until the session expires (7 days after sign-in), exchanged
         *                     once at /auth/refresh. Browsers should rely on the httpOnly cookie
         *                     set with the same value and never store this field.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description RS256-signed JWT access token.
             */
            access_token: string;
            /**
             * Refresh Token
             * @description RS256-signed JWT refresh token.
             */
            refresh_token: string;
            /**
             * Token Type
             * @description Token scheme.
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Seconds until the access token expires.
             */
            expires_in: number;
            /**
             * Access Expires At Ms
             * @description Access token expiry [UTC ms].
             */
            access_expires_at_ms: number;
            /**
             * Session Expires At Ms
             * @description When the session ends and a new sign-in is needed [UTC ms].
             */
            session_expires_at_ms: number;
            /** Username */
            username: string;
            /** Role */
            role: string;
        };
        /** TripCause */
        TripCause: {
            /** Parameter */
            parameter: string;
            /** Value */
            value: number;
            /** Threshold */
            threshold: number;
            /** Timestamp Ms */
            timestamp_ms: number;
        };
        /** TurbineStateResponse */
        TurbineStateResponse: {
            /** Electrical Power W */
            electrical_power_w: number;
            /** Shaft Power W */
            shaft_power_w: number;
            /** Enthalpy In J Kg */
            enthalpy_in_j_kg: number;
            /** Enthalpy Out J Kg */
            enthalpy_out_j_kg: number;
            /** Exhaust Pressure Pa */
            exhaust_pressure_pa: number;
            /** Steam Flow Kg S */
            steam_flow_kg_s: number;
            /** Timestamp Ms */
            timestamp_ms: number;
            /** Steam Temp In K */
            steam_temp_in_k: number;
            /** Exhaust Temp K */
            exhaust_temp_k: number;
        };
        /**
         * TurbineStatusResponse
         * @description Current turbine state as returned by GET /api/v1/status.
         *     All values in SI units, matching TurbineStateMsg fields exactly.
         */
        TurbineStatusResponse: {
            /**
             * Electrical Power W
             * @description Net electrical output [W].
             */
            electrical_power_w: number;
            /**
             * Shaft Power W
             * @description Mechanical shaft power [W].
             */
            shaft_power_w: number;
            /**
             * Enthalpy In J Kg
             * @description Inlet specific enthalpy [J/kg].
             */
            enthalpy_in_j_kg: number;
            /**
             * Enthalpy Out J Kg
             * @description Outlet specific enthalpy [J/kg].
             */
            enthalpy_out_j_kg: number;
            /**
             * Exhaust Pressure Pa
             * @description Condenser back-pressure [Pa].
             */
            exhaust_pressure_pa: number;
            /**
             * Steam Flow Kg S
             * @description Steam mass flow [kg/s].
             */
            steam_flow_kg_s: number;
            /**
             * Timestamp Ms
             * @description UTC epoch milliseconds.
             */
            timestamp_ms: number;
            /**
             * Steam Temp In K
             * @description Turbine inlet superheated steam temperature [K].
             * @default 0
             */
            steam_temp_in_k: number;
        };
        /** UserCreateRequest */
        UserCreateRequest: {
            /**
             * Username
             * @example shift.operator
             */
            username: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "operator" | "engineer" | "admin";
        };
        /** UserPageResponse */
        UserPageResponse: {
            /** Items */
            items: components["schemas"]["UserResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Role
             * @description None if the account has no role.
             */
            role: ("viewer" | "operator" | "engineer" | "admin") | null;
            /** Is Active */
            is_active: boolean;
            /** Created At Ms */
            created_at_ms: number;
            /** Last Login At Ms */
            last_login_at_ms: number | null;
            /**
             * Open Sessions
             * @description Sessions that can still be refreshed.
             */
            open_sessions: number;
        };
        /**
         * UserUpdateRequest
         * @description Change the role, block or unblock. Either change closes the user's sessions.
         */
        UserUpdateRequest: {
            /** Role */
            role?: ("viewer" | "operator" | "engineer" | "admin") | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValveCommandRequest
         * @description Request body for POST /api/v1/commands/valve.
         *     Requires minimum role: operator.
         *     All three valve positions must be provided together to avoid
         *     partial state updates that could destabilise the control loop.
         */
        ValveCommandRequest: {
            /**
             * Fuel Valve
             * @description Fuel valve position [0.0 = closed, 1.0 = fully open].
             * @example 0.75
             */
            fuel_valve: number;
            /**
             * Feedwater Valve
             * @description Feedwater valve position [0.0 – 1.0].
             * @example 0.6
             */
            feedwater_valve: number;
            /**
             * Steam Valve
             * @description Turbine admission valve position [0.0 – 1.0].
             * @example 0.5
             */
            steam_valve: number;
            /**
             * Spray Valve
             * @description Attemperator spray valve position [0.0 – 1.0]; omitted keeps it.
             * @example 0.25
             */
            spray_valve?: number | null;
        };
        /** ValveCommandValues */
        ValveCommandValues: {
            /** Fuel Valve */
            fuel_valve: number;
            /** Feedwater Valve */
            feedwater_valve: number;
            /** Steam Valve */
            steam_valve: number;
            /** Spray Valve */
            spray_valve: number;
            /**
             * Source
             * @description operator | pid | safety | scheduler
             */
            source: string;
            /** Operator Id */
            operator_id: string;
            /** Timestamp Ms */
            timestamp_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    platform_api_v1_platform_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    change_password_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    get_plant_state_api_v1_plant_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantStateResponse"];
                };
            };
        };
    };
    get_simulation_status_api_v1_simulation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatusResponse"];
                };
            };
        };
    };
    list_scenarios_api_v1_simulation_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
        };
    };
    pause_api_v1_simulation_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationAckResponse"];
                };
            };
        };
    };
    resume_api_v1_simulation_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationAckResponse"];
                };
            };
        };
    };
    set_speed_api_v1_simulation_speed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_api_v1_simulation_step_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_scenario_api_v1_simulation_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inject_fault_api_v1_simulation_faults_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_all_faults_api_v1_simulation_faults_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultAckResponse"];
                };
            };
        };
    };
    clear_fault_api_v1_simulation_faults__fault_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenario_runs_api_v1_simulation_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRunPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_valve_command_api_v1_commands_valve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValveCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_load_demand_api_v1_commands_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadDemandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_control_mode_api_v1_commands_mode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlModeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_setpoints_api_v1_commands_setpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetpointRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_emergency_stop_api_v1_commands_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResetRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plc_status_api_v1_plc_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PLCStatusResponse"];
                };
            };
        };
    };
    get_history_api_v1_history_get: {
        parameters: {
            query?: {
                measurement?: string;
                /** @description [UTC epoch ms] */
                start_ms?: number | null;
                /** @description [UTC epoch ms] */
                end_ms?: number | null;
                /** @description Maximum number of points. */
                limit?: number;
                /** @description Comma-separated field names; all when omitted. */
                fields?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kpis_api_v1_kpi_get: {
        parameters: {
            query?: {
                /** @description [UTC epoch ms] */
                start_ms?: number | null;
                /** @description [UTC epoch ms] */
                end_ms?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alarms_api_v1_alarms_get: {
        parameters: {
            query?: {
                /** @description Only open alarms: not both cleared and acknowledged. */
                active_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlarmResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alarm_history_api_v1_alarms_history_get: {
        parameters: {
            query?: {
                severity?: ("warning" | "critical") | null;
                parameter?: string | null;
                /** @description Raised at or after [UTC ms]. */
                from_ms?: number;
                /** @description Raised at or before [UTC ms]. */
                to_ms?: number;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlarmPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_all_api_v1_alarms_ack_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeAllRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alarm_api_v1_alarms__alarm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alarm_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlarmDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alarm_api_v1_alarms__alarm_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alarm_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_entries_api_v1_audit_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                username?: string | null;
                method?: string | null;
                /** @description Path prefix, e.g. /api/v1/commands. */
                endpoint?: string | null;
                status?: number | null;
                /** @description e.g. 400 for every refusal. */
                min_status?: number | null;
                /** @description [UTC epoch ms] */
                from_ms?: number | null;
                /** @description [UTC epoch ms] */
                to_ms?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                /** @description Only active or blocked. */
                active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_users__user_id__password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_sessions_api_v1_users__user_id__revoke_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsRevokedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
